import React, { useState, useEffect } from 'react';
import { GHANA_REGIONS } from '../lib/constants';
import { generateUniqueMemberId, insertNewMember, uploadAvatarFile, verifyAndUseRegCode, fetchSystemSettings } from '../lib/supabase';
import { AdminRole, EducationLevel, Gender, Member, SystemSettings } from '../types';
import { UserPlus, CheckCircle2, Copy, Printer, ArrowRight, ShieldCheck, Mail, User, MapPin, RefreshCw, AlertCircle, Key, Crown, UserCheck, Upload, Image as ImageIcon, X, GraduationCap, Briefcase, Calendar, ShieldAlert } from 'lucide-react';

interface MemberRegistrationProps {
  onGoToChecker: (memberId?: string) => void;
}

export const MemberRegistration: React.FC<MemberRegistrationProps> = ({ onGoToChecker }) => {
  const [role, setRole] = useState<AdminRole>('main_admin');
  const [regCodeInput, setRegCodeInput] = useState('');
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [region, setRegion] = useState<string>('Greater Accra');
  const [educationLevel, setEducationLevel] = useState<EducationLevel>('Degree');
  const [gender, setGender] = useState<Gender>('Male');
  const [profession, setProfession] = useState('Volunteer First Aider');
  const [societyPosition, setSocietyPosition] = useState('Community Volunteer');
  const [dateJoined, setDateJoined] = useState(new Date().toISOString().slice(0, 10));
  const [avatarFile, setAvatarFile] = useState<File | null>(null);
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [registeredMember, setRegisteredMember] = useState<Member | null>(null);
  const [copiedId, setCopiedId] = useState(false);
  const [systemSettings, setSystemSettings] = useState<SystemSettings>({
    allow_sub_admin_reg: true,
    is_voting_window_open: true,
    require_auth_codes: true,
  });

  useEffect(() => {
    fetchSystemSettings().then((s) => setSystemSettings(s));
  }, []);

  const handleAvatarChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      if (file.size > 5 * 1024 * 1024) {
        setErrorMsg('Avatar image size must be smaller than 5MB.');
        return;
      }
      setAvatarFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setAvatarPreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleRemoveAvatar = () => {
    setAvatarFile(null);
    setAvatarPreview(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName.trim() || !email.trim() || !region) {
      setErrorMsg('Please fill out all required fields.');
      return;
    }

    if (role === 'sub_admin') {
      if (!systemSettings.allow_sub_admin_reg) {
        setErrorMsg('⛔ Sub-Admin registration permissions are currently TURNED OFF by the Super-Admin Overlord.');
        return;
      }

      if (systemSettings.require_auth_codes && !regCodeInput.trim()) {
        setErrorMsg('Sub-Admins strictly require a valid "Registration Authorization Code" generated by the Main Admin.');
        return;
      }
    }

    setSubmitting(true);
    setErrorMsg(null);

    try {
      // If Sub-Admin and auth code enforcement is enabled, verify and consume code
      if (role === 'sub_admin' && systemSettings.require_auth_codes && regCodeInput.trim()) {
        const verifyRes = await verifyAndUseRegCode(regCodeInput);
        if (!verifyRes.valid) {
          setErrorMsg(verifyRes.error || 'Invalid or already used Registration Authorization Code.');
          setSubmitting(false);
          return;
        }
      }

      // Upload avatar file if selected
      let profilePictureUrl: string | null = null;
      if (avatarFile) {
        const uploadRes = await uploadAvatarFile(avatarFile);
        if (uploadRes.error) {
          console.warn('Avatar upload fallback warning:', uploadRes.error);
        }
        profilePictureUrl = uploadRes.url;
      }

      const generatedId = generateUniqueMemberId();

      const res = await insertNewMember({
        full_name: fullName.trim(),
        email: email.trim(),
        region,
        member_id: generatedId,
        profile_picture_url: profilePictureUrl,
        education_level: educationLevel,
        gender,
        profession,
        society_position: societyPosition,
        date_joined: dateJoined,
        created_by_admin_id: role,
      });

      if (res.error) {
        setErrorMsg(res.error);
      } else if (res.member) {
        setRegisteredMember(res.member);
        // Clear form fields
        setFullName('');
        setEmail('');
        setRegion('Greater Accra');
        setRegCodeInput('');
        setAvatarFile(null);
        setAvatarPreview(null);
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'An error occurred during registration.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleCopyId = () => {
    if (!registeredMember) return;
    navigator.clipboard.writeText(registeredMember.member_id);
    setCopiedId(true);
    setTimeout(() => setCopiedId(false), 2000);
  };

  const handlePrintCard = () => {
    window.print();
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 sm:py-12">
      {/* Page Title */}
      <div className="text-center mb-8 no-print">
        <div className="inline-flex items-center justify-center w-14 h-14 bg-red-100 text-red-700 rounded-full mb-3 shadow-sm border border-red-200">
          <UserPlus className="w-7 h-7 text-red-600" />
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold font-heading text-gray-900 tracking-tight">
          New Member & Volunteer Registration
        </h2>
        <p className="text-sm sm:text-base text-gray-600 max-w-lg mx-auto mt-1">
          Enroll into the official Ghana Red Cross Society directory. Role-based access control enforces registration codes for Sub-Admins.
        </p>
      </div>

      {/* Main Form or Success Display Card */}
      <div className="bg-white rounded-2xl shadow-xl border-2 border-red-100 overflow-hidden">
        {/* Card Header Bar */}
        <div className="bg-gradient-to-r from-red-700 to-red-800 text-white px-6 py-4 flex items-center justify-between no-print">
          <span className="font-bold text-sm tracking-wider uppercase font-heading flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-red-200" />
            Ghana Red Cross Society Enrollment Form
          </span>
          <span className="text-xs text-red-100 font-mono font-medium">
            Membership Portal 2026
          </span>
        </div>

        <div className="p-6 sm:p-10">
          {errorMsg && (
            <div className="mb-6 p-4 bg-red-50 border-l-4 border-red-600 rounded-r-xl text-red-800 text-sm flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
              <div>
                <span className="font-bold block text-red-900">Registration Error</span>
                {errorMsg}
              </div>
            </div>
          )}

          {/* REGISTERED SUCCESS CARD VIEW */}
          {registeredMember ? (
            <div className="py-2">
              <div className="text-center mb-6">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-emerald-100 text-emerald-600 rounded-full mb-3 animate-bounce">
                  <CheckCircle2 className="w-10 h-10 text-emerald-600" />
                </div>
                <h3 className="text-2xl font-black font-heading text-gray-900">
                  Registration Successful!
                </h3>
                <p className="text-sm text-gray-600 mt-1">
                  Your record has been inserted into the database with initial status <strong>⚪ NOT ACTIVE</strong>.
                </p>
              </div>

              {/* Printable Official Red/White Member ID Slip */}
              <div className="bg-gradient-to-br from-white via-red-50/30 to-white rounded-2xl border-2 border-red-600 p-6 sm:p-8 shadow-xl max-w-xl mx-auto mb-8 relative">
                <div className="flex items-center justify-between border-b border-red-200 pb-4 mb-4">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 bg-red-600 text-white rounded-lg flex items-center justify-center font-bold text-xs relative">
                      <div className="relative w-4 h-4 flex items-center justify-center">
                        <div className="absolute w-4 h-1 bg-white rounded-xs"></div>
                        <div className="absolute h-4 w-1 bg-white rounded-xs"></div>
                      </div>
                    </div>
                    <div>
                      <h4 className="font-extrabold font-heading text-gray-900 text-sm">
                        OFFICIAL MEMBERSHIP CARD
                      </h4>
                      <p className="text-xs text-red-600 font-bold uppercase tracking-wider">
                        Ghana Red Cross Society
                      </p>
                    </div>
                  </div>
                  <span className="text-xs font-mono bg-red-100 text-red-800 font-bold px-2.5 py-1 rounded">
                    NOT ACTIVE
                  </span>
                </div>

                {/* Member ID Display Box */}
                <div className="bg-white p-5 rounded-xl border-2 border-dashed border-red-300 text-center mb-6 shadow-inner flex flex-col items-center">
                  {registeredMember.profile_picture_url && (
                    <div className="w-20 h-20 rounded-full border-2 border-red-600 overflow-hidden mb-3 shadow-md">
                      <img
                        src={registeredMember.profile_picture_url}
                        alt={registeredMember.full_name}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  )}
                  <span className="text-xs uppercase font-extrabold text-gray-500 tracking-widest block mb-1">
                    Your Generated Member ID Number
                  </span>
                  <span className="text-3xl sm:text-4xl font-mono font-black text-red-600 tracking-wider">
                    {registeredMember.member_id}
                  </span>
                  <p className="text-xs text-gray-400 mt-2 font-medium">
                    Please copy or write down this Member ID. You will use it to check your dues clearance.
                  </p>
                </div>

                {/* Member Data Grid */}
                <div className="grid grid-cols-2 gap-3 text-xs sm:text-sm">
                  <div>
                    <span className="text-gray-400 uppercase font-bold text-[10px] block">
                      Full Name
                    </span>
                    <span className="font-bold text-gray-900">{registeredMember.full_name}</span>
                  </div>
                  <div>
                    <span className="text-gray-400 uppercase font-bold text-[10px] block">
                      Ghana Region
                    </span>
                    <span className="font-bold text-gray-900">{registeredMember.region}</span>
                  </div>
                  <div>
                    <span className="text-gray-400 uppercase font-bold text-[10px] block">
                      Email
                    </span>
                    <span className="font-medium text-gray-800 break-all">
                      {registeredMember.email}
                    </span>
                  </div>
                  <div>
                    <span className="text-gray-400 uppercase font-bold text-[10px] block">
                      Issued Date
                    </span>
                    <span className="font-medium text-gray-800">
                      {new Date(registeredMember.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap items-center justify-center gap-3 no-print">
                <button
                  type="button"
                  onClick={handleCopyId}
                  className="px-5 py-2.5 bg-red-600 hover:bg-red-700 text-white font-bold rounded-xl text-sm flex items-center gap-2 transition-all cursor-pointer shadow-md"
                >
                  {copiedId ? (
                    <>
                      <CheckCircle2 className="w-4 h-4 text-emerald-300" />
                      <span>Copied to Clipboard!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy Member ID</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={handlePrintCard}
                  className="px-5 py-2.5 bg-white hover:bg-gray-50 text-gray-800 border-2 border-gray-300 font-bold rounded-xl text-sm flex items-center gap-2 transition-all cursor-pointer"
                >
                  <Printer className="w-4 h-4 text-gray-600" />
                  <span>Print Slip</span>
                </button>

                <button
                  type="button"
                  onClick={() => onGoToChecker(registeredMember.member_id)}
                  className="px-5 py-2.5 bg-red-50 hover:bg-red-100 text-red-700 border border-red-200 font-bold rounded-xl text-sm flex items-center gap-2 transition-all cursor-pointer"
                >
                  <span>Check Status Now</span>
                  <ArrowRight className="w-4 h-4" />
                </button>

                <button
                  type="button"
                  onClick={() => setRegisteredMember(null)}
                  className="px-4 py-2.5 text-xs text-gray-500 hover:text-gray-800 font-bold underline"
                >
                  Register Another Member
                </button>
              </div>
            </div>
          ) : (
            /* STANDARD REGISTRATION FORM WITH ROLE SWITCHER */
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Registration Role Switcher */}
              <div className="p-4 bg-gray-50 rounded-xl border border-gray-200">
                <label className="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-2">
                  Registration Role Access Level
                </label>
                <div className="grid grid-cols-2 gap-3">
                  <button
                    type="button"
                    onClick={() => {
                      setRole('main_admin');
                      setErrorMsg(null);
                    }}
                    className={`p-3 rounded-xl border-2 flex items-center justify-center gap-2 font-bold text-xs cursor-pointer transition-all ${
                      role === 'main_admin'
                        ? 'bg-red-600 text-white border-red-700 shadow-md'
                        : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                    }`}
                  >
                    <Crown className="w-4 h-4" />
                    <span>Main Admin (Direct Access)</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setRole('sub_admin');
                      setErrorMsg(null);
                    }}
                    className={`p-3 rounded-xl border-2 flex items-center justify-center gap-2 font-bold text-xs cursor-pointer transition-all ${
                      role === 'sub_admin'
                        ? 'bg-red-600 text-white border-red-700 shadow-md'
                        : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                    }`}
                  >
                    <UserCheck className="w-4 h-4" />
                    <span>Sub-Admin (Code Required)</span>
                  </button>
                </div>
              </div>

              {/* Sub-Admin Warning if disabled */}
              {role === 'sub_admin' && !systemSettings.allow_sub_admin_reg && (
                <div className="p-4 bg-red-100 border-2 border-red-500 rounded-xl text-red-900 text-xs sm:text-sm font-bold flex items-center gap-2">
                  <ShieldAlert className="w-5 h-5 text-red-600 shrink-0" />
                  <span>
                    Sub-Admin registration permissions are currently TURNED OFF by Super-Admin settings. Submissions will be blocked.
                  </span>
                </div>
              )}

              {/* Sub-Admin Code Input Box if Sub-Admin Role */}
              {role === 'sub_admin' && systemSettings.require_auth_codes && (
                <div className="p-4 bg-amber-50 border-2 border-amber-300 rounded-xl space-y-2">
                  <label
                    htmlFor="reg_code_input"
                    className="block text-xs font-bold text-amber-950 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <Key className="w-4 h-4 text-amber-700" />
                    Registration Authorization Code <span className="text-red-600">*</span>
                  </label>
                  <input
                    id="reg_code_input"
                    type="text"
                    required={systemSettings.require_auth_codes}
                    value={regCodeInput}
                    onChange={(e) => setRegCodeInput(e.target.value.toUpperCase())}
                    placeholder="e.g. REG-9X2Y"
                    className="w-full px-4 py-2.5 bg-white border border-amber-300 rounded-lg font-mono font-bold text-base text-gray-900 uppercase focus:outline-none focus:ring-2 focus:ring-amber-500"
                  />
                  <p className="text-[11px] text-amber-800">
                    Sub-Admins must enter an active authorization code generated by the Main Admin. Codes can only be used once. (Try demo code: <strong className="font-mono">REG-9X2Y</strong> or <strong className="font-mono">REG-8402</strong>)
                  </p>
                </div>
              )}

              {/* Full Name & Email Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label
                    htmlFor="full_name"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <User className="w-4 h-4 text-red-600" />
                    Full Name <span className="text-red-600">*</span>
                  </label>
                  <input
                    id="full_name"
                    type="text"
                    required
                    value={fullName}
                    onChange={(e) => setFullName(e.target.value)}
                    placeholder="e.g. Kwame Mensah"
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-medium text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all placeholder:text-gray-400"
                  />
                </div>

                <div>
                  <label
                    htmlFor="email"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <Mail className="w-4 h-4 text-red-600" />
                    Email Address <span className="text-red-600">*</span>
                  </label>
                  <input
                    id="email"
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="e.g. kwame.mensah@redcrossghana.org"
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-medium text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all placeholder:text-gray-400"
                  />
                </div>
              </div>

              {/* Region & Gender Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label
                    htmlFor="region_select"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <MapPin className="w-4 h-4 text-red-600" />
                    Ghana Region <span className="text-red-600">*</span>
                  </label>
                  <select
                    id="region_select"
                    required
                    value={region}
                    onChange={(e) => setRegion(e.target.value)}
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-bold text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all cursor-pointer"
                  >
                    {GHANA_REGIONS.map((r) => (
                      <option key={r} value={r}>
                        {r} Region
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label
                    htmlFor="gender_select"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <User className="w-4 h-4 text-red-600" />
                    Gender <span className="text-red-600">*</span>
                  </label>
                  <select
                    id="gender_select"
                    required
                    value={gender}
                    onChange={(e) => setGender(e.target.value as Gender)}
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-bold text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all cursor-pointer"
                  >
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                  </select>
                </div>
              </div>

              {/* Education Level & Profession Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label
                    htmlFor="education_select"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <GraduationCap className="w-4 h-4 text-red-600" />
                    Education Level <span className="text-red-600">*</span>
                  </label>
                  <select
                    id="education_select"
                    required
                    value={educationLevel}
                    onChange={(e) => setEducationLevel(e.target.value as EducationLevel)}
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-bold text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all cursor-pointer"
                  >
                    <option value="JHS">JHS (Junior High)</option>
                    <option value="SHS">SHS (Senior High)</option>
                    <option value="Diploma">Diploma</option>
                    <option value="Degree">Bachelor Degree</option>
                    <option value="Masters">Masters Degree</option>
                    <option value="PhD">Doctorate (PhD)</option>
                  </select>
                </div>

                <div>
                  <label
                    htmlFor="profession_input"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <Briefcase className="w-4 h-4 text-red-600" />
                    Profession / Occupation
                  </label>
                  <input
                    id="profession_input"
                    type="text"
                    value={profession}
                    onChange={(e) => setProfession(e.target.value)}
                    placeholder="e.g. Nurse, Teacher, Student, Engineer"
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-medium text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all placeholder:text-gray-400"
                  />
                </div>
              </div>

              {/* Position in Society & Date Joined Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label
                    htmlFor="society_position_input"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <Crown className="w-4 h-4 text-red-600" />
                    Society Position / Role
                  </label>
                  <input
                    id="society_position_input"
                    type="text"
                    value={societyPosition}
                    onChange={(e) => setSocietyPosition(e.target.value)}
                    placeholder="e.g. Youth Coordinator, First Aider, Volunteer"
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-medium text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all placeholder:text-gray-400"
                  />
                </div>

                <div>
                  <label
                    htmlFor="date_joined_input"
                    className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5"
                  >
                    <Calendar className="w-4 h-4 text-red-600" />
                    Date Joined Society
                  </label>
                  <input
                    id="date_joined_input"
                    type="date"
                    required
                    value={dateJoined}
                    onChange={(e) => setDateJoined(e.target.value)}
                    className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-xl font-bold text-gray-900 focus:outline-none focus:ring-4 focus:ring-red-500/20 focus:border-red-600 transition-all"
                  />
                </div>
              </div>

              {/* Profile Picture Upload (Supabase Avatars Bucket) */}
              <div>
                <label className="block text-sm font-bold text-gray-800 mb-1.5 uppercase tracking-wide flex items-center gap-1.5">
                  <ImageIcon className="w-4 h-4 text-red-600" />
                  Member Profile Picture
                  <span className="text-gray-400 font-normal text-xs">(Optional - Upload to Supabase Storage)</span>
                </label>

                <div className="flex flex-col sm:flex-row items-center gap-4 bg-gray-50 p-4 border-2 border-dashed border-gray-300 rounded-xl hover:border-red-400 transition-colors">
                  {avatarPreview ? (
                    <div className="relative w-24 h-24 rounded-full overflow-hidden border-2 border-red-600 shadow-sm shrink-0 bg-white">
                      <img src={avatarPreview} alt="Preview" className="w-full h-full object-cover" />
                      <button
                        type="button"
                        onClick={handleRemoveAvatar}
                        className="absolute top-1 right-1 bg-red-600 text-white rounded-full p-1 hover:bg-red-700 transition-colors cursor-pointer"
                        title="Remove image"
                      >
                        <X className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  ) : (
                    <div className="w-20 h-20 rounded-full bg-red-50 border-2 border-red-200 flex items-center justify-center text-red-400 shrink-0">
                      <User className="w-10 h-10" />
                    </div>
                  )}

                  <div className="flex-1 text-center sm:text-left">
                    <label
                      htmlFor="avatar_upload_input"
                      className="inline-flex items-center gap-2 px-4 py-2.5 bg-white border border-gray-300 hover:bg-red-50 hover:border-red-300 text-gray-800 font-bold rounded-lg text-xs cursor-pointer shadow-sm transition-all"
                    >
                      <Upload className="w-4 h-4 text-red-600" />
                      <span>{avatarFile ? 'Change Profile Picture' : 'Upload Passport Photo'}</span>
                    </label>
                    <input
                      id="avatar_upload_input"
                      type="file"
                      accept="image/*"
                      onChange={handleAvatarChange}
                      className="hidden"
                    />
                    <p className="text-[11px] text-gray-500 mt-1.5">
                      Supports JPG, PNG or WEBP up to 5MB. Photo will be saved to Supabase <code className="bg-gray-200 px-1 rounded text-red-700 font-mono">avatars</code> bucket.
                    </p>
                  </div>
                </div>
              </div>

              {/* Note on ID & Default Status */}
              <div className="bg-red-50/70 p-4 rounded-xl border border-red-200 text-xs text-red-900 flex items-start gap-2.5">
                <ShieldCheck className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold block text-red-950">
                    Automatic Member ID Generation
                  </span>
                  Submitting this form creates a database record with default status{' '}
                  <strong>⚪ NOT ACTIVE</strong>. Payment clearance is verified by the administrator.
                </div>
              </div>

              {/* Submit Button */}
              <div className="pt-2">
                <button
                  type="submit"
                  disabled={submitting}
                  className="w-full py-4 bg-red-600 hover:bg-red-700 text-white font-extrabold text-base rounded-xl shadow-lg hover:shadow-red-600/30 transition-all flex items-center justify-center gap-2 cursor-pointer active:scale-95 font-heading uppercase tracking-wider"
                >
                  {submitting ? (
                    <>
                      <RefreshCw className="w-5 h-5 animate-spin" />
                      <span>Creating Member Record...</span>
                    </>
                  ) : (
                    <>
                      <UserPlus className="w-5 h-5" />
                      <span>Submit & Generate Member ID</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};

